cnmysql: server=localhost;port=3307;database=db_security;user=root;password=Aforo255#2019
cnpostgres: Server=localhost;Port=5434;Database=db_account;User Id=postgres;Password=Aforo255#2019;
cnmongo: mongodb://aforo255:Aforo255#2019@localhost:27018
cnmongodatabase: db_history
cnsql: Server=localhost,1434;Database=db_account;User Id=sa;Password=Aforo255#2019;
cnmariadb: server=localhost;port=3310;database=db_notification;user=root;password=Aforo255#2019
cnredis: localhost
enviroment: development
jaeger:enabled: true
jaeger:serviceName: security-service
jaeger:udpHost: localhost
jaeger:udpPort: 6831
jaeger:maxPacketSize: 0
jaeger:sampler: const
seq:enabled: true
seq:url: http://localhost:5341
seq:token: NoEnsLTylmWmWeeeifYN
